### PR TITLE
update EFI Maker

### PR DESCRIPTION
**Pull request by btwise**

### CODE REVIEW

**Comment by btwise** [comment]
@mackie100 
EFI Maker should add SSDT, Kext, and Drivers selection list to allow users to choose whether to join and download corresponding files according to the existing function definition; I tested that I could not download the file from other resource addresses, it only from GitHub; After the generation is completed, add a prompt to choose whether to open the generated config file from OCC for perfect editing!

**Comment by btwise** [comment]
@mackie100 
`UEFI-->OUTPUT-->GopPassThrough` prompt cannot display Chinese language!
All files that EFI Maker needs to download should be distributed to other repository addresses, such as OpenCore Bootloer, Kext, and Drivers, so that users who cannot access GitHub can download them

**Comment by mackie100** [comment]
> @mackie100
> `UEFI-->OUTPUT-->GopPassThrough` prompt cannot display Chinese language!
> All files that EFI Maker needs to download should be distributed to other repository addresses, such as OpenCore Bootloer, Kext, and Drivers, so that users who cannot access GitHub can download them,It is very difficult for Chinese users to download the latest Release files from the GitHub repository!
> image

That's a redundant option, already exists in preferences panel. Only kext files use official github repository.

**Comment by mackie100** [comment]
> @mackie100
> EFI Maker should add SSDT, Kext, and Drivers selection list to allow users to choose whether to join and download corresponding files according to the existing function definition; I tested that I could not download the file from other resource addresses, it only from GitHub; After the generation is completed, add a prompt to choose whether to open the generated config file from OCC for perfect editing!

EFI maker download corresponding files according to Dortania's configurations.

**Pull request merged**
