### PR TITLE
update translate

### PR DESCRIPTION
**Pull request by btwise**
@mackie100 
Since my gitcode.net warehouse has stopped operating, the new warehouse cannot obtain the direct download address, so please delete the csdn warehouse address from the occ source code! 

The access address for my new warehouse is: https://gitcode.com/btwise/OClocalizations, but I can't get its raw download address. Can you check if you can get a physical download address for use in occ?

### CODE REVIEW

**Comment by mackie100** [comment]
> @mackie100 Since my gitcode.net warehouse has stopped operating, the new warehouse cannot obtain the direct download address, so please delete the csdn warehouse address from the occ source code!
> 
> The access address for my new warehouse is: https://gitcode.com/btwise/OClocalizations, but I can't get its raw download address. Can you check if you can get a physical download address for use in occ?

This link return "This web page is currently under review..." message.

**Comment by btwise** [comment]
@mackie100 
Now my new repository is accessible at: https://gitcode.com/btwise/OCClocalizations
If the original address of the files in the repository e.x.: `https://raw.gitcode.com/btwise/OCClocalizations/raw/master/README.md`,
The prefix address is: `https://raw.gitcode.com/btwise/OCClocalizations/raw/master/xxxxxx`

**Comment by btwise** [comment]
@mackie100 
You can add a new China repository address to the OCC option

**Comment by mackie100** [comment]
> @mackie100 You can add a new China repository address to the OCC option

@btwise You need to update https://github.com/mackie100/OCClocalizations/commit/aa8d53d7eddf6a56375d9e7d057d39019731d208#diff-ceb8199545fae4b3f31946f981c0d8d409525e5cb05c5f8667f54eb5269149fb
[https://github.com/mackie100/OCClocalizations/commit/aa8d53d7eddf6a56375d9e7d057d39019731d208#diff-ceb8199545fae4b3f31946f981c0d8d409525e5cb05c5f8667f54eb5269149fb](url)
in your repository.

**Comment by btwise** [comment]
> > @mackie100 You can add a new China repository address to the OCC option
> 
> @btwise You need to update [aa8d53d](https://github.com/mackie100/OCClocalizations/commit/aa8d53d7eddf6a56375d9e7d057d39019731d208) in your repository.

already update to gitcode.com

**Pull request merged**
